#include<stdio.h>
#include<conio.h>
struct student
{
char nm[20];
int roll;
int add[30];
char sesssion[10];
};
void disp(struct student)
{
clrscr();
struct student s;
printf("\n Enter the name");
scanf("%s",s1.nm);
gets (s1.nm);
printf("\n Enter the roll");
scanf("%d",s1.num);
printf("\n Enter the address");
fflush(stdin);
gets(s1.address);
printf("\n Enter the age:-");
scanf("%d".&s1.age);
printf("\n Enter the session");
gets(s1.session);
getch();
}
void disp(struct student s2);
{
printf("\n name=%s",s1.nm)